### PR TITLE
Allow nesting of TextInput inside other components

### PR DESCRIPTION
**Pull request by dcvz**
This adds support for something like:

```js
<Form>
  <View style={[styles.textContainer, { marginTop: 30 }]}>
    <TextInput
      placeholder={'XXX'}
      {...textInputSharedProps}
      value={this.state.xxx}
      onChangeText={text => this.setState({ xxx: text })}
    />
  </View>
  <View style={[styles.textContainer, { marginTop: 12 }]}>
    <TextInput
      placeholder={'XX'}
      {...textInputSharedProps}
      value={this.state.xx}
      onSubmitEditing={this.joinXX}
      onChangeText={text => this.setState({ xx: text })}
    />
  </View>
</Form>
```

### CODE REVIEW

**Comment by zackify** [comment]
I wasn't checking for children properly, made a commit that should fix this issue with less changes: https://github.com/zackify/react-native-autofocus/commit/d16222a88fe5eb7cbbde103b83400153876d19a2 download the latest version and let me know if there's still something wrong. Thanks for the PR though!!

**Comment by dcvz** [comment]
Your index doesn't change though; because a new index is started when you recursively call.

**Comment by zackify** [comment]
Good point, this should work then: https://github.com/zackify/react-native-autofocus/commit/cc124539753255b57273a32c4cb07b099a8b50a7

**Comment by dcvz** [comment]
You will also want to keep this line: https://github.com/zackify/react-native-autofocus/pull/3/files#diff-df55e4f73a007e05610a65d5d01534ebR16

name doesn't always come from `type.name` :(

**Comment by zackify** [comment]
@dcvz so on web I can check for child.props.name. That isn't needed on native. What if I check for value? and assume it's an input? Or just add the displayName check. What do you think?

**Comment by dcvz** [comment]
your solution isn't working still; will keep using mine for now. already spent some time debugging the first implementation. my guess is that index is still incorrect.

btw, I don't think the `...child.props` is necessary as it should get cloned

**Comment by zackify** [comment]
Good point, I'll debug this in RN confused why it wouldn't work and yours does and merge yours if i cant figure it out

**Comment by zackify** [comment]
Sorry, can you try 0.0.6 first. I was missing adding the recursive index.

**Comment by dcvz** [comment]
seems to work :)

**Comment by zackify** [comment]
Sweet!

**Pull request closed without merging**
